import type { GrammarElement } from "../linguistic-element.js"
import { g } from "./helpers.js"

// Skill 11 — Particules & connecteurs (80 éléments)
// IDs 300-379, frequency = rang intra-skill

export const skill11Data: ReadonlyArray<GrammarElement> = [
  // --- Particules (24) ---
  g(300, "だ", "Copula asserting identity or state", 1, 1),
  g(301, "は", "Marks the topic of a sentence", 2, 1),
  g(302, "が", "Marks subject or introduces contrast between clauses", 3, 2),
  g(303, "を", "Marks the direct object of a verb", 4, 1),
  g(304, "に", "Marks target, location, time, passive agent, or purpose", 5, 5),
  g(305, "の", "Indicates possession, nominalization, or apposition", 6, 3),
  g(306, "で", "Marks means, location of action, or cause", 7, 3),
  g(307, "と", "Marks quotation, conjunction, accompaniment, or automatic conditional", 8, 4),
  g(308, "も", "Indicates inclusion or emphasis (also, even)", 9, 1),
  g(309, "か", "Marks questions or alternatives", 10, 2),
  g(310, "から", "Marks spatial/temporal origin, causal reason, or clause connector", 11, 3),
  g(311, "へ", "Marks direction of movement", 12, 1),
  g(312, "まで", "Marks an endpoint in space or time", 13, 1),
  g(313, "より", "Marks comparison or formal origin", 14, 2),
  g(314, "だけ", "Restricts scope to only the marked element", 15, 1),
  g(315, "しか", "Restricts scope with obligatory negative predicate", 16, 1),
  g(316, "や", "Lists items non-exhaustively", 17, 1),
  g(317, "など", "Indicates examples or approximation (things like)", 18, 1),
  g(318, "ばかり", "Indicates recency or exclusivity (just did, nothing but)", 19, 2),
  g(319, "ほど", "Expresses degree, extent, or proportional comparison", 20, 2),
  g(320, "くらい/ぐらい", "Expresses approximation in quantity or degree", 21, 1),
  g(321, "よ", "Sentence-final particle asserting or informing", 22, 1),
  g(322, "ね", "Sentence-final particle seeking confirmation or agreement", 23, 1),
  g(323, "わ", "Sentence-final particle adding soft emphasis", 24, 1),

  // --- Connecteurs (12) ---
  g(324, "けど/けれど(も)", "Connects clauses with contrast or softening (but, although)", 25, 3),
  g(325, "ので", "Connects clauses with objective causal relationship (because)", 26, 1),
  g(326, "のに", "Connects clauses expressing frustrated expectation (despite)", 27, 1),
  g(327, "し", "Lists reasons or qualities cumulatively (and also)", 28, 1),
  g(328, "て (conjonctif)", "Connects sequential actions or states (and then, by doing)", 29, 1),
  g(329, "たら", "Conditional connector expressing hypothetical or temporal sequence", 30, 1),
  g(330, "ば", "Conditional connector expressing hypothetical condition", 31, 1),
  g(331, "なら", "Conditional connector based on contextual supposition", 32, 1),
  g(332, "ても/でも", "Concessive connector (even if, even though)", 33, 1),
  g(333, "ながら", "Marks simultaneous actions (while doing)", 34, 1),
  g(334, "たり", "Lists representative actions non-exhaustively (doing things like)", 35, 1),
  g(335, "つつ", "Formal simultaneous action connector (while, formal register)", 36, 1),

  // --- Expressions fonctionnelles formelles (16) ---
  g(336, "に関して/に関する", "Formal expression marking topic (regarding, concerning)", 37, 2),
  g(337, "について/につき", "Marks the subject of discussion (about, concerning)", 38, 2),
  g(338, "に対して/に対する", "Marks direction of attitude or contrast (towards, against)", 39, 2),
  g(339, "にとって", "Marks perspective holder (for someone, from one's standpoint)", 40, 1),
  g(340, "において/における", "Formal locative or contextual marker (in, at)", 41, 2),
  g(341, "によって/により", "Marks means, agent, or variation (by, depending on)", 42, 3),
  g(342, "に基づいて", "Marks basis for action or judgment (based on)", 43, 1),
  g(343, "をもとに", "Marks source material or inspiration (based on, from)", 44, 1),
  g(344, "を通じて/を通して", "Marks medium or duration (through, throughout)", 45, 2),
  g(345, "にわたって", "Marks extent across time or space (over, spanning)", 46, 1),
  g(346, "に沿って", "Marks adherence to a line or standard (along, in line with)", 47, 1),
  g(347, "に応じて", "Marks proportional response (according to, depending on)", 48, 1),
  g(348, "をはじめ", "Marks a leading example in a list (starting with, including)", 49, 1),
  g(349, "を込めて", "Marks infused feeling or intention (with feeling put in)", 50, 1),
  g(350, "に伴って", "Marks accompanying change (along with, as)", 51, 1),
  g(351, "とともに", "Marks simultaneous occurrence or companionship (together with)", 52, 2),

  // --- Connecteurs de nuance (20) ---
  g(
    352,
    "上で (うえで)",
    "Marks precondition or context for action (after doing, in doing)",
    53,
    2,
  ),
  g(353, "上に (うえに)", "Adds information cumulatively (in addition to, on top of)", 54, 1),
  g(354, "以上 (いじょう)", "Marks a committed premise (since, now that)", 55, 1),
  g(
    355,
    "一方 (いっぽう)",
    "Introduces contrasting or simultaneous situation (while, on the other hand)",
    56,
    1,
  ),
  g(356, "反面 (はんめん)", "Introduces the opposite aspect (on the other hand)", 57, 1),
  g(357, "かわりに", "Marks substitution or compensation (instead of, in exchange)", 58, 2),
  g(358, "次第 (しだい)", "Marks immediate trigger or dependency (as soon as, depends on)", 59, 2),
  g(359, "限り (かぎり)", "Marks condition boundary (as long as, unless)", 60, 2),
  g(360, "に限って", "Marks ironic specificity (precisely when, only in this case)", 61, 1),
  g(361, "からには", "Marks committed premise with obligation (now that, since)", 62, 1),
  g(362, "以来 (いらい)", "Marks temporal starting point (since, ever since)", 63, 1),
  g(363, "たびに", "Marks recurring trigger (every time, whenever)", 64, 1),
  g(364, "まま", "Marks unchanged state (as is, leaving unchanged)", 65, 1),
  g(365, "とおり/どおり", "Marks conformity to a model (as, in the way)", 66, 2),
  g(366, "くせに", "Marks critical concession with negative nuance (even though, despite)", 67, 1),
  g(367, "わりに", "Marks unexpected proportion (considering, for)", 68, 1),
  g(368, "あまり", "Marks excess leading to consequence (so much that)", 69, 1),
  g(369, "からこそ", "Emphasizes causal specificity (precisely because)", 70, 1),
  g(370, "ものの", "Formal concessive connector (although, written register)", 71, 1),
  g(371, "ものなら", "Marks daring or wishful conditional (if one could, if you dare)", 72, 2),

  // --- Particules de nuance (8) ---
  g(372, "こそ", "Emphatic particle highlighting the marked element (it is X that)", 73, 1),
  g(373, "さえ", "Marks extreme example or minimal condition (even, if only)", 74, 2),
  g(374, "すら/ですら", "Formal emphatic particle marking extreme case (even)", 75, 1),
  g(375, "だらけ", "Suffix marking abundance, often negative (full of, covered in)", 76, 1),
  g(376, "っけ", "Sentence-final particle expressing vague recollection (wasn't it?)", 77, 1),
  g(377, "ものか", "Rhetorical particle expressing strong denial (no way, as if)", 78, 1),
  g(378, "向け (むけ)", "Suffix marking intended target audience (aimed at, for)", 79, 1),
  g(379, "抜き (ぬき)", "Suffix marking deliberate omission (without, leaving out)", 80, 1),
]
