import type { GrammarPoint } from "../grammar-point.js"
import { g } from "./helpers.js"

// Skill 12 — Conjugaisons & patterns (93 éléments)
// IDs 380-472, frequency = rang intra-skill

export const skill12Data: ReadonlyArray<GrammarPoint> = [
  // --- Conjugaisons pures (28) ---
  g(
    380,
    "です/ではありません",
    "Copula polite forms: affirmative, negative, past, past negative",
    1,
    4,
  ),
  g(381, "ます form", "Polite non-past verb form across verb groups", 2, 3),
  g(382, "ません", "Polite negative verb form across verb groups", 3, 3),
  g(383, "ました", "Polite past verb form across verb groups", 4, 3),
  g(384, "ませんでした", "Polite past negative verb form across verb groups", 5, 3),
  g(385, "ない form", "Plain negative verb form with stem changes per verb group", 6, 3),
  g(386, "た form", "Plain past verb form with onbin sound changes for godan", 7, 4),
  g(387, "なかった", "Plain past negative form built on ない stem", 8, 1),
  g(388, "て form", "Conjunctive verb form with same onbin changes as た form", 9, 4),
  g(389, "ている", "Progressive or resultative aspect (ongoing action or resulting state)", 10, 2),
  g(390, "potential form", "Expresses ability (can do) with stem changes per verb group", 11, 3),
  g(391, "passive form", "Expresses passive voice with stem changes per verb group", 12, 3),
  g(
    392,
    "causative form",
    "Expresses causation (make/let do) with stem changes per verb group",
    13,
    3,
  ),
  g(393, "imperative form", "Direct command form with stem changes per verb group", 14, 3),
  g(394, "prohibitive な", "Negative command using dictionary form plus な", 15, 1),
  g(395, "volitional form", "Expresses volition or suggestion (let's, I'll) per verb group", 16, 3),
  g(396, "conditional ば form", "Hypothetical conditional with stem changes per verb group", 17, 3),
  g(397, "conditional たら form", "Temporal or hypothetical conditional built on た form", 18, 1),
  g(398, "causative-passive", "Combined causative and passive (made to do against will)", 19, 3),
  g(399, "い-adj negative (くない)", "い-adjective negative form replacing い with くない", 20, 1),
  g(400, "い-adj past (かった)", "い-adjective past form replacing い with かった", 21, 1),
  g(401, "い-adj past neg (くなかった)", "い-adjective past negative form", 22, 1),
  g(402, "い-adj adverb (く)", "い-adjective to adverb conversion replacing い with く", 23, 1),
  g(403, "い-adj て form (くて)", "い-adjective conjunctive form replacing い with くて", 24, 1),
  g(404, "な-adj forms", "な-adjective inflections: な, じゃない, だった, じゃなかった", 25, 4),
  g(405, "ないで", "Negative conjunctive meaning 'without doing'", 26, 1),
  g(406, "なくて", "て-form of negative, expressing cause or sequence", 27, 1),
  g(407, "ず/ずに", "Formal negative conjunctive meaning 'without doing'", 28, 2),

  // --- Patterns — transformation verbale (65) ---
  g(408, "たい", "Expresses first-person desire (want to do), conjugates like い-adj", 29, 2),
  g(409, "たがる", "Expresses observed third-person desire (wants to do)", 30, 1),
  g(410, "てもいい", "Expresses permission (may, allowed to)", 31, 1),
  g(411, "てはいけない", "Expresses prohibition (must not, not allowed to)", 32, 1),
  g(412, "なければならない", "Expresses obligation (must do) with variant forms", 33, 3),
  g(413, "なくてもいい", "Expresses lack of obligation (don't have to)", 34, 1),
  g(414, "てくれる (construction)", "Construct て-form plus くれる for receiving favors", 35, 1),
  g(415, "てあげる (construction)", "Construct て-form plus あげる for giving favors", 36, 1),
  g(416, "てもらう (construction)", "Construct て-form plus もらう for requesting favors", 37, 1),
  g(417, "ことができる", "Formal expression of ability (can do, be able to)", 38, 1),
  g(418, "ことがある", "Expresses experience or occasional occurrence", 39, 2),
  g(419, "ようにする", "Expresses effort toward a habit or goal (try to, make sure to)", 40, 1),
  g(
    420,
    "ようになる",
    "Expresses gradual change in ability or state (come to, become able)",
    41,
    1,
  ),
  g(421, "てしまう", "Expresses completion or regret (end up doing, completely)", 42, 2),
  g(422, "ておく", "Expresses preparatory action (do in advance, leave as is)", 43, 1),
  g(423, "てみる", "Expresses trying an action to see the result (try doing)", 44, 1),
  g(424, "たばかり", "Expresses recency of completed action (just did)", 45, 1),
  g(
    425,
    "ところだ",
    "Expresses temporal proximity to an action (about to, in the middle of, just now)",
    46,
    3,
  ),
  g(426, "はずだ", "Expresses expectation or logical conclusion (should be, expected to)", 47, 1),
  g(
    427,
    "そうだ (appearance)",
    "Expresses appearance based on direct observation (looks like)",
    48,
    2,
  ),
  g(428, "そうだ (hearsay)", "Reports information from another source (I heard that)", 49, 1),
  g(429, "ようだ/みたいだ", "Expresses resemblance or conjecture (seems like)", 50, 2),
  g(430, "らしい", "Expresses conjecture based on evidence (apparently, it seems)", 51, 1),
  g(431, "つもりだ", "Expresses intention or plan (intend to)", 52, 1),
  g(432, "ことにする", "Expresses a personal decision (decide to)", 53, 1),
  g(433, "ことになる", "Expresses an external decision or outcome (it has been decided)", 54, 1),
  g(434, "てある", "Expresses a resultant state from deliberate action (is in a state of)", 55, 1),
  g(435, "ていく", "Expresses continuation into the future (go on doing, from now)", 56, 1),
  g(436, "てくる", "Expresses change up to now or approaching (come to, until now)", 57, 1),
  g(437, "すぎる", "Expresses excess (too much) attached to verb stem or adj stem", 58, 1),
  g(438, "やすい", "Expresses ease of action attached to verb stem (easy to do)", 59, 1),
  g(439, "にくい", "Expresses difficulty of action attached to verb stem (hard to do)", 60, 1),
  g(
    440,
    "受身 indirect passive",
    "Indirect passive expressing negative impact on the subject",
    61,
    1,
  ),
  g(
    441,
    "させてもらう/させていただく",
    "Humble request pattern combining causative with receiving",
    62,
    2,
  ),
  g(442, "てほしい", "Expresses desire for someone else to do something", 63, 1),
  g(443, "たらどう", "Suggests an action to the listener (why don't you)", 64, 1),
  g(444, "べきだ", "Expresses moral obligation or strong recommendation (should)", 65, 1),
  g(445, "なさい", "Polite command form using verb stem (softer than imperative)", 66, 1),
  g(446, "ば〜ほど", "Expresses proportional correlation (the more... the more)", 67, 1),
  g(447, "がる", "Expresses observed third-person emotion or sensation (show signs of)", 68, 1),
  g(448, "ようにと", "Reports an indirect command or request (tell someone to)", 69, 1),
  g(449, "かもしれない", "Expresses possibility or uncertainty (might, maybe)", 70, 1),
  g(450, "にちがいない", "Expresses strong certainty (must be, no doubt)", 71, 1),
  g(451, "わけだ", "Expresses logical conclusion or impossibility with わけがない", 72, 2),
  g(452, "ものだ", "Expresses nostalgia or general truth (used to, that's how it is)", 73, 2),
  g(453, "ざるを得ない", "Expresses unavoidable obligation (can't help but, have to)", 74, 2),
  g(
    454,
    "わけにはいかない",
    "Expresses inability due to social or moral constraint (can't afford to)",
    75,
    2,
  ),
  g(455, "っぽい", "Suffix expressing resemblance or tendency (-ish, seems like)", 76, 1),
  g(456, "がち", "Suffix expressing negative tendency (tend to, prone to)", 77, 1),
  g(457, "気味 (ぎみ)", "Suffix expressing slight degree or touch of something", 78, 1),
  g(458, "たとえ〜ても", "Concessive construction with hypothetical emphasis (even if)", 79, 1),
  g(
    459,
    "どんなに〜ても",
    "Concessive construction emphasizing degree (no matter how much)",
    80,
    1,
  ),
  g(460, "てたまらない", "Expresses unbearable degree of sensation or emotion", 81, 1),
  g(461, "てならない", "Expresses irrepressible feeling (can't help feeling)", 82, 1),
  g(462, "てしょうがない", "Expresses irrepressible state (can't help it, helplessly)", 83, 1),
  g(463, "ないではいられない", "Double negative expressing compulsion (can't help doing)", 84, 1),
  g(464, "かける/かけ", "Expresses incomplete action or being about to (half-done)", 85, 1),
  g(
    465,
    "きる/きれる/きれない",
    "Expresses complete or exhaustive action (completely, can't fully)",
    86,
    2,
  ),
  g(466, "得る (うる/える)", "Expresses possibility of occurrence (possible, can happen)", 87, 2),
  g(467, "つつある", "Expresses ongoing process of change (in the process of)", 88, 1),
  g(
    468,
    "ないことはない",
    "Double negative expressing reluctant possibility (not that one can't)",
    89,
    1,
  ),
  g(469, "しかない", "Expresses lack of alternatives (have no choice but)", 90, 1),
  g(470, "ほかない/ほかはない", "Formal expression of no alternative (have no choice but)", 91, 1),
  g(471, "抜く (ぬく)", "Expresses thorough or persevering completion (do thoroughly)", 92, 1),
  g(472, "てこそ", "Emphasizes that only through this action can a result be achieved", 93, 1),
]
